version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: nomadway_db
    environment:
      POSTGRES_USER: nomadway_user
      POSTGRES_PASSWORD: nomadway_password
      POSTGRES_DB: nomadway_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: